services:
  - type: web
    name: learnai-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: NIM_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
